const PlannersAction = {
    ADDDRAFT: 'ADD_DRAFT',
    SETDRAFTS: 'SET_DRAFTS',
    ADDFAV: 'ADD_FAV',
    SETFAVS: 'SET_FAVS',
    CLEARDRAFTS: 'CLEAR_DRAFTS',
    CLEARFAVS: 'CLEAR_FAVS',
    LOADFAVS: 'LOAD_FAVS',
    LOADDRAFTS: 'LOAD_DRAFTS',
    SETPLANNERS: 'SET_PLANNERS',
    CLEARPLANNER: 'CLEAR_PLANNERS',
}
export default PlannersAction
